version: '3'

services:
  db:
    image: postgres:16-alpine
    restart: always
    networks:
      - boards-network
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 4gaBoards
      POSTGRES_PASSWORD: notpassword
      POSTGRES_INITDB_ARGS: "-A scram-sha-256"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d 4gaBoards"]
      interval: 5s
      timeout: 5s
      retries: 10

  4gaBoards:
    image: ghcr.io/rargames/testactions2:latest
    restart: always
    networks:
      - boards-network
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - 3000:1337
    environment:
      BASE_URL: http://localhost:3000
      SECRET_KEY: notsecretkey
      DATABASE_URL: postgresql://postgres:notpassword@db/4gaBoards
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
networks:
  boards-network: